x is printed as 3
the second one gives an error because x is not initiated outside the method